name: Driving-Teacher
on: push

jobs: 
  build:
    name: Simple building workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.1.404
        
      - name: Restore dependencies
        run: dotnet resore
        
      - name: Build project
        run: dotnet build --configuration Release --no-restore
        